### PR TITLE
feat: create editor abstract class #2

### PR DESCRIPTION
**Pull request by yu-emily**

### CODE REVIEW

**Comment by yu-emily** [comment]
Hi @ashwinkjoseph,
I changed the abstract class name to Editor to make it simpler.

I am unclear about some parts of the implementation for Ace Editor.

**(1)  The parameters for the class constructor.** 
--Right now I have it with 3 constructors: (i) the div element, (ii) the options for styling the editor (if provided), and (iii) the unique id (if provided).

**(2)  The "onSwitch" mentioned in the acceptance criteria.** 
--It is stated that the class accepts a parameter "type" and saves it as a onSwitch state, but for both minimize and close functions, we'll call the onSwitch method with a value. I think what's confusing for me is, is onSwitch supposed to be a property/parameter or method?

--For now, I have a dummy function called onSwitch outside the class and is included in the implementation example:
```
/*function onSwitch(status){
    let test = document.getElementById("text");
    test.innerHTML = `Status: ${status}`;
}*/
```

**Comment by yu-emily** [comment]
Hi @ashwinkjoseph ,
I have changed the options from mode to language like you said.
I added a unminimize function to the AceEditor class so that it'll unminimize the editor and allow a smoother process for testing. Other buttons are added to the demo html also.
I'm still not sure about whether the close function is working as intended.
Let me know if these changes are good to go or need more editing. Thanks!

**Comment by jonathanrdelgado** [comment]
I just took a look and my overall impression is we can create a React functional component in which we pass all of these methods as props. I think we can do away with the concept of the abstract classes as the component itself can do this by virtue of passed props.
A very very basic example of this:
```js
const Editor = ({ props }) => {
  return <div onClick={props.minimize}>Minimize</div>
};

<Editor minimize={myMinimizeFunc} />
```

If we go with a functional component, we can leverage React hooks and effects as well for things like mounting/unmounting, more on that at https://reactjs.org/docs/hooks-intro.html

In terms of the data side, and calling methods remotely from the component, I think using Redux as a parent data store is going to be the solution. We can then dispatch items remotely in to trigger changes to the component state. Here is some documentation on Redux hooks, which would be a good complement to the hooks stuff I was mentioning above https://react-redux.js.org/api/hooks

**Comment by yu-emily** [comment]
Hi @ashwinkjoseph @jonathanrdelgado ,
It looks like there's a React library that implements the Ace Editor.
https://github.com/securingsincity/react-ace

I'm wondering whether we could use it to integrate with our project and add custom functions on top of that so that our Editor functional component can call other methods from the Terminal and others.

**Comment by jonathanrdelgado** [comment]
Yeah, I definitely think that is a good approach!

**Comment by yu-emily** [comment]
Hi @jonathanrdelgado and @ashwinkjoseph ,
Here's an update of what I have implemented so far on my end.
I've decided that based on the specs, there're two main functionalities that the editor component will implement.
(1) Styling Issues/Editor Customization and 
(2) Storing the Editor Instance with Redux/Rematch.

For (1), it's mostly covering these previous specs:
```
- Accept an HTML Div Element and mount to it while initializing
- Accept custom styles when initializing and should also allow for customization after initialization.
- Should have a method for minimizing
- Should have a method for closing
- Accept callback function which will be called with appropriate status when minimizing or closing
```
The react-ace library covers most of the styling issues. I was thinking, it might be beneficial for future users of The Programming Foundation to have the flexibility to control the look of the code editor. For instance, the font size, the dark/light theme (and maybe allow users to switch between different programming languages for coding.)

Here's an example of implementing a toggle for light and dark themes for the code editor:
```js
const EditorTheme = () =>{
    const [checked, setChecked] = useState(true);
    return(
      <input
            type="checkbox"
            id="theme"
            checked={checked}
            onChange={() => setChecked(!checked)}
        />
        <label for="theme">Dark Mode</label>
         <AceEditor
            theme={checked ? 'monokai' : 'tomorrow'}
        />
  );
}
```
Here's another example of how I was thinking of implementing the minimizing functionality.
We can pass in a value for the minimize prop. True allows a user to click on a minimize button, and false allows the button to not be displayed.
```js
const EditorMinimize = (props) =>{
    const {minimize} = props;
    const [display, setDisplay] = useState(true);
    function handleMinimize(){
        setDisplay(!display);
    }
    return(
      {minimize ? <button onClick={handleMinimize}>Minimize</button> : ''}
       <AceEditor
            style={{display: display ? 'block' : 'none'}}
        />
  );
}

<EditorMinimize minimize={true}/> 
```

As for (2), I was playing around a bit with Rematch, and the implementation I have here is a rough way of storing the editor's content to the data store.

```js
//models.js
export const editorStorage = {
    state: [],
    reducers: {
        addEditor: (state, code) => {
            if(state.length === 0){
                let id = 0;
                return [...state, {editorId: id, content: code}];
            }
            let newId = state[state.length -1].editorId + 1;
            return [...state, {editorId: newId, content: code}];
        },
        destroyEditor: (state, id) => {
            return state.filter(editor => editor.id !== id)
        }
    }
}

//EditorRedux.js
function EditorRedux(props){
    const [code, setCode] = useState(null);
    
    function getContent(currentValue){
        setCode(JSON.stringify(currentValue));
    }

    return(
        <React.Fragment>
            <button onClick={() => props.addToStorage(code)}>Save Editor</button>
            <AceEditor 
                theme="monokai"
                onChange={getContent}
            />
        </React.Fragment>
    );
}

const mapState = state => ({
    editorStorage: state.editorStorage
});

const mapDispatch = dispatch => ({
    addToStorage: (code) => dispatch.editorStorage.addEditor(code)
});

export default connect(mapState, mapDispatch)(EditorRedux);
```
I think I'll need help finishing implementing the Editor component. Most of the part is I have yet to implement the close function where the editor instance is destroyed and the data is removed from the data store. I would also need more guidance on what a use case for the editor would be like to write a better implementation. What things will be modified by us to create different kinds of instances for the editor and what things will be accessible to the users of TPF? Where would the editor be implemented?

Anyways, the main things I probably need help with working on is:
(1) integrating the Editor component to Gatsby
(2) connecting the Editor component with Redux/Rematch
(3) creating/destroying multiple Editor instances

**Pull request closed without merging**
